config/routes.rb
Rails.application.routes.draw do

  root to: 'projects#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show, :edit, :update, :destroy]

  resources :projects, shallow: true do
		resources :features do
			resources :requests
		end
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
	belongs_to :project
	has_many :requests

  def get_assigned_dev
    request = self.requests.select {|request| request.assigned == true}.first
    request ? request.user.email : 'Not Assigned'
  end
end

app/models/project.rb
class Project < ApplicationRecord

	extend WithUserAssociationExtension

	belongs_to :user
	has_many :features, dependent: :destroy

	has_attached_file :image, :styles => { :large => "700x700>", :medium => "300x300>", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def progress
		assigned_features = []
		self.features.each do |feature|
			assigned_features += feature.requests.select {|request| request.assigned}
		end

		if (self.features.length) != 0
			p ((assigned_features.length / self.features.length.to_f)*100).to_i.to_s + '%'
		else
		end
	end
end

app/models/request.rb
class Request < ApplicationRecord

	extend WithUserAssociationExtension

	belongs_to :feature
	belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:github]
  has_many :projects
  has_many :requests

  has_attached_file :image, :styles => { :medium => "300x300>", :bigthumb => "200x200>", :thumb => "75x75>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end


end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension

  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController

	def new
		@feature = Feature.new
		@project = Project.find(params[:project_id])
	end

	def create
		@project = Project.find(params[:project_id])
		@project.features.create(feature_params)
		redirect_to project_path(@project)
	end

  def show
    @feature = Feature.find(params[:id])
   	@dev = @feature.get_assigned_dev
  end

	private

	def feature_params
		params.require(:feature).permit(:name, :description, :deadline)
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create_with_user(project_params, current_user)
    redirect_to project_path(@project)
  end

 def show
   @project = Project.find(params[:id])
 end

private

  def project_params
    params.require(:project).permit(:name, :description, :launch_date, :image)
  end


end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

	def create
		@feature = Feature.find(params[:feature_id])
		@request = @feature.requests.create_with_user({assigned: false}, current_user)
		render json: {new_status: 'Your request has been sent'}
	end

	def update
		@request = Request.find(params[:id])
		@feature = @request.feature
		@request.update(assigned: true)
    UserMailer.confirmation_email(@request.user, @feature).deliver_now
		redirect_to feature_path(@feature)
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def github
    
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, :except => [:show]

  def show
    @user = User.find(params[:id])
    @projects_started = Project.where(user: current_user)
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user= User.find(params[:id])
    @user.update(user_params)
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :description, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def prettify_date(date)
		date.strftime('%d/%m/%Y')
	end

	def format_date(date)
		date.strftime('%Y/%m/%d')
	end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/features/_request_list.html.erb
<% if @dev == 'Not Assigned' %>

  <h3>Requests Received for Feature:</h3>

<div class="feature-requests">

  <% if @feature.requests.any? %>
    <% @feature.requests.each do |request| %>
    <ul class="feature-request-ul">
      <li> <h4><%= request.user.email %></h4>  ||
      <%= link_to 'Select', request_path(request), method: :patch %></li>
    </ul>
    <% end %>
  <% else %>
    No requests received yet
  <% end %>
<% end %>

</div>

app/views/features/new.html.erb
<div class="form-wrapper">
  
  <h2>Add a feature</h2>

  <%= form_for [@project, @feature] do |f| %>
    
    <div class="field">
      <%= f.label 'Feature Name:' %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label 'Description:' %>
      <%= f.text_field :description %>
    </div>

    <div class="field">
      <%= f.label 'Deadline:' %>
      <%= f.date_field :deadline, placeholder: 'dd/mm/yy' %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  
  <% end %>

</div>

app/views/features/show.html.erb
<div class="feature-container">
	<h3>Project:</h3> <h4><%= @feature.project.name %></h4>
	<h3>Feature:</h3> <h4><%= @feature.name %></h4>
	<h3>Description:<h3> <h4><%= @feature.description %></h4>
	<h3>Assigned Developer:</h3> <h4><%= @dev %></h4>

	<%= render "request_list" %>
</div>

app/views/layouts/_navbar.html.erb
<ul class='navbar'>

  <li class='nav-content-left'><%= link_to 'Start a project', new_project_path(@project) %></li>
  <li class='nav-content-left'><%= link_to "About us" %></li>
  <li class='navbar-center'><a href='/'><img class='full-logo' src='/images/full_logo.png'/></a></li>  

  <% if current_user %>

    <li class='nav-content-right'><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
    <li class='nav-content-right'><%= link_to "My profile", current_user %></li>
  
  <% else %>

    <li class='nav-content-right'><%= link_to "Sign in", new_user_session_path %></li>
    <li class='nav-content-right'><%= link_to "Sign up", new_user_registration_path %></li>
    <li class='nav-content-right'><%= link_to "Sign in with Github", user_github_omniauth_authorize_path %></li>

  <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrowdCode</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  </head>

  <body>

    <%= render "/layouts/navbar" %>

    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>

    <%= yield %>

    <%= render "/layouts/footer" %>

  </body>
</html>

app/views/projects/_display_assigned_dev.html.erb
<div class='display_assigned_dev'>

    <% if feature.requests.any? %>

        <% if feature.requests.any? {|request| request.assigned} %>
            This feature has already been assigned to a user.
        <% else %>
            <%= render 'not_assigned_request_message', feature: feature %>
        <% end %>
    <% else %>
        <%= render 'not_assigned_request_message', feature: feature %>
    <% end %>

  </div>

app/views/projects/_feature_list.html.erb
<table>
	<tr>
    <th>Feature Name</th>
    <th>Description</th>
    <th>Deadline</th>
    <th>Status</th>
  </tr>

	<% @project.features.each do |feature| %>
		<tr>
		  <td><%= link_to feature.name, feature_path(feature) %></td>
		  <td><%= feature.description %></td>
		  <td><%= format_date(feature.deadline) %></td>

		  <td><%= render "display_assigned_dev", :feature => feature %></td>
		</tr>

	<% end %>

</table>

app/views/projects/_not_assigned_request_message.html.erb
<div>Not assigned ||
<span class=request-status></span><%= link_to 'Send Request', feature_requests_path(feature), class: 'request-link'%></div>

app/views/projects/_project_list.erb
<% @projects = @projects.sort_by {|project| project.launch_date} %>

	<% @projects.each do |project| %>

		<div class='project-container'>
			<div class='image-container'><%= image_tag project.image.url(:medium), class: 'project-image' %></div>
			<div class='text-container'>
				<p class='bold-text'><%= link_to project.name, project_path(project) %></p>
				<p><%= project.description %><p>
					<br>
					<br>
				<p><span class='bold-text'>Launch date: </span><%= prettify_date(project.launch_date) %></p>
				<p><span class='bold-text'>Posted by: </span> <%= User.find(project.user_id).email %></p>
				<div class="progress-container">
					<div style="width: <%=project.progress%>" class="progressbar">
					</div>
				</div>

			</div>
		</div>
	<% end %>

app/views/projects/index.html.erb
<div class='homepage-container'>

	<div class='image-container'>
		<img class='homepage-pic'src='./images/desk.jpg' />
		<span class='picture-text'>Our mission is to help bring tech projects to life</span>
	</div>

	<div>
		<div class='sub-title'>Recommended for you:</div>
		<div class='projects-recommended'>
			<%= render "project_list" %>
		</div>
	</div>

	<div class='footer'>
   <a href='/'><img class='full-logo-footer' src='/images/full_logo.png'/></a>
 	</div>

</div>

app/views/projects/new.html.erb
<div class="form-wrapper">
  
  <h2>Start a project</h2>
  
    <%= form_for @project, html: {multipart: true} do |f| %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %><br />
      </div>
      
      <div class="field" id="description_field">
        <%= f.label :description %>
        <%= f.text_field :description %><br />
      </div>
      
      <div class="field">
        <%= f.label :launch_date %>
        <%= f.date_field :launch_date %>
      </div>

       <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
      
      <div class="actions">
        <%= f.submit %></div>
    <% end %>

</div>

app/views/projects/show.html.erb
<div class='project-pic-container'>
	<%= image_tag @project.image.url(:large), class: 'project-main-image' %>
<div>

<div class='project-title'><%= @project.name %></div>
<div class='project-description'><%= @project.description%></div>


<%= render "feature_list" %>

<div class='add-feature-link'>
	<%= link_to 'Add Feature', new_project_feature_path(@project), class:'add-ft-link-text' %>
</div>


<div class='footer'>
   <a href='/'><img class='full-logo-footer' src='/images/full_logo.png'/></a>
 </div>

app/views/users/_edit_profile.html.erb
<% if current_user.id == @user.id %>
  <%= link_to "Edit profile", edit_user_path %>
<% end %>

app/views/users/_form.html.erb
<div class="form-wrapper">
  <h2>Edit profile</h2>

    <%= form_for @user, html: {multipart: true} do |f| %>
      
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>

      <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
      
      <div class="actions">
        <%= f.submit %>
      </div>

    <% end %>

</div>

app/views/users/_project_started.html.erb
<% @projects_started.each do |project| %>
  <p> <%= link_to "#{project.name}", project_path(project) %> </p>
<% end %>

app/views/users/edit.html.erb
<%  if current_user.id == @user.id %>
<%= render "form" %>
<% else %>

<strong> Sorry, you cannot edit another user's profile <strong>

<% end %>

app/views/users/show.html.erb
<div class='profile-container-side'>
  <div class='name'> Hi, I'm <%= @user.name %></div>
  <div class='profile_picture'><%= image_tag @user.image.url(:bigthumb) %></div>
  <h2> E-mail: </h2> <div class='email'> <%= @user.email %> </div>
  <h4 id='edit_profile'> <%= render "edit_profile" %> </h4>
</div>

<div class='profile-container-body'>
  <h3> About Me: </h3>
  <div class='user_description'><%= @user.description %> </div>
  <h3> Projects Started: </h3>
  <div class='project_links'> <%= render "project_started" %> </div>
</div>